### ISSUE TITLE
License confusion!

### ISSUE THREAD

**Issue by ccpu** [ombr/referentiel#14]
Thank you for this library, just wondering if you have intentionally choose two license for this library? or it has been a mistake? `package.json`  license is set to "ISC", but "LICENSE" file to "GPL-3.0".

**Comment by ombr** [comment]
Hi @ccpu,

I just updated the license to GPL-3.0 in package.json. Do you have any requirements for the license ?

Thanks.

Luc

**Comment by ccpu** [comment]
Hi @Ombr,

Unfortunately  I wont be able to use GPL-3.0 licensed library in my project, but its ok I have found different technique to solve same problem.

Thanks.

**Comment by ombr** [comment]
Hi @ccpu,

Do you mind telling me the technique/library you found ?

Thanks.

Luc

**Comment by ccpu** [comment]
Sure, I am using [CSSDesinger](https://github.com/LabsRS-Dev/CSSDesinger/blob/0482a751f8e4fe622594174e9eecb249fc3cf789/src/public/js/pre_load/convertPointFromPageToNode.js), its based on [Yaffle gist](https://gist.github.com/Yaffle/1145197).
